name: payment_getway
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fluttertoast: ^8.0.7
  get: ^4.1.4
  dio: ^4.0.0
  #  flutter_money_formatter: ^0.8.3
  font_awesome_flutter: ^9.1.0
  flutter_rating_bar: ^4.0.0
  razorpay_flutter: ^1.2.6
  paytm_allinonesdk: ^1.0.3
  http_auth:
  http:
  webview_flutter: ^3.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


